name: Build

on:
  workflow_dispatch:
  
jobs:
  build_wheels:
    name: Build wheels
    strategy:
      matrix:
        os-arch: ["manylinux_x86_64", "win_amd64", "macosx_x86_64", "macosx_arm64"]
        python-version: ["3.10"]
        cibw-python: ["cp38", "cp39", "cp310","cp311"]
    runs-on: ${{ matrix.os }}
      
    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
      - name: Install dependence
        run: python -m pip install pybind11 cibuildwheel scikit-build
  
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

#       - uses: actions/upload-artifact@v3
#         with:
#           path: ./wheelhouse/*.whl
